[2024-05-09T09:13:42.980+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T09:13:43.013+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T04:00:00+00:00 [queued]>
[2024-05-09T09:13:43.021+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T04:00:00+00:00 [queued]>
[2024-05-09T09:13:43.021+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T09:13:43.036+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 04:00:00+00:00
[2024-05-09T09:13:43.041+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=296) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T09:13:43.042+0000] {standard_task_runner.py:63} INFO - Started process 301 to run task
[2024-05-09T09:13:43.041+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T04:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmphemz8vzs']
[2024-05-09T09:13:43.043+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask except_friday_run_database_task
[2024-05-09T09:13:43.057+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T09:13:43.093+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T04:00:00+00:00 [running]> on host 5d069ed3d57a
[2024-05-09T09:13:43.172+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T04:00:00+00:00'
[2024-05-09T09:13:43.173+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T09:13:43.201+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T09:13:43.202+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T09:13:43.213+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T04:00:00+00:00, execution_date=20240509T040000, start_date=20240509T091343, end_date=20240509T091343
[2024-05-09T09:13:43.256+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T09:13:43.270+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T09:13:43.273+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T17:14:12.368+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T17:14:12.410+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T04:00:00+00:00 [queued]>
[2024-05-09T17:14:12.417+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T04:00:00+00:00 [queued]>
[2024-05-09T17:14:12.418+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T17:14:12.437+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 04:00:00+00:00
[2024-05-09T17:14:12.445+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=268) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T17:14:12.447+0000] {standard_task_runner.py:63} INFO - Started process 277 to run task
[2024-05-09T17:14:12.447+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T04:00:00+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmp94pm8tje']
[2024-05-09T17:14:12.455+0000] {standard_task_runner.py:91} INFO - Job 196: Subtask except_friday_run_database_task
[2024-05-09T17:14:12.477+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T17:14:12.559+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T04:00:00+00:00 [running]> on host 2ac721f319c6
[2024-05-09T17:14:12.693+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T04:00:00+00:00'
[2024-05-09T17:14:12.698+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T17:14:12.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T17:14:12.734+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/single_dag.py", line 101, in insert_data_to_table
    cur.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.

[2024-05-09T17:14:12.770+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T04:00:00+00:00, execution_date=20240509T040000, start_date=20240509T171412, end_date=20240509T171412
[2024-05-09T17:14:12.786+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 196 for task except_friday_run_database_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.
; 277)
[2024-05-09T17:14:12.831+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T17:14:12.849+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T17:14:12.853+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T18:32:08.101+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T18:32:08.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T04:00:00+00:00 [queued]>
[2024-05-09T18:32:08.260+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T04:00:00+00:00 [queued]>
[2024-05-09T18:32:08.262+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T18:32:08.288+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 04:00:00+00:00
[2024-05-09T18:32:08.294+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=410) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T18:32:08.295+0000] {standard_task_runner.py:63} INFO - Started process 430 to run task
[2024-05-09T18:32:08.298+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T04:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpix0jmtpl']
[2024-05-09T18:32:08.300+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask except_friday_run_database_task
[2024-05-09T18:32:08.402+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T18:32:08.634+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T04:00:00+00:00 [running]> on host def55370f167
[2024-05-09T18:32:09.044+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T04:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T04:00:00+00:00'
[2024-05-09T18:32:09.046+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T18:32:09.150+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T18:32:09.151+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T18:32:09.237+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T04:00:00+00:00, execution_date=20240509T040000, start_date=20240509T183208, end_date=20240509T183209
[2024-05-09T18:32:09.304+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T18:32:09.407+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T18:32:09.411+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
