[2024-05-09T09:13:42.976+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T09:13:43.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-09T09:13:43.015+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-09T09:13:43.015+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T09:13:43.027+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 00:00:00+00:00
[2024-05-09T09:13:43.032+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=294) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T09:13:43.032+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpp_w35f7_']
[2024-05-09T09:13:43.033+0000] {standard_task_runner.py:63} INFO - Started process 300 to run task
[2024-05-09T09:13:43.034+0000] {standard_task_runner.py:91} INFO - Job 60: Subtask except_friday_run_database_task
[2024-05-09T09:13:43.047+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T09:13:43.085+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T00:00:00+00:00 [running]> on host 5d069ed3d57a
[2024-05-09T09:13:43.162+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T00:00:00+00:00'
[2024-05-09T09:13:43.164+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T09:13:43.193+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T09:13:43.194+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T09:13:43.203+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T00:00:00+00:00, execution_date=20240509T000000, start_date=20240509T091343, end_date=20240509T091343
[2024-05-09T09:13:43.248+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T09:13:43.262+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T09:13:43.264+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T17:14:12.386+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T17:14:12.438+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-09T17:14:12.448+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-09T17:14:12.451+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T17:14:12.474+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 00:00:00+00:00
[2024-05-09T17:14:12.481+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=269) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T17:14:12.482+0000] {standard_task_runner.py:63} INFO - Started process 283 to run task
[2024-05-09T17:14:12.482+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T00:00:00+00:00', '--job-id', '198', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpim1cvwst']
[2024-05-09T17:14:12.484+0000] {standard_task_runner.py:91} INFO - Job 198: Subtask except_friday_run_database_task
[2024-05-09T17:14:12.514+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T17:14:12.591+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T00:00:00+00:00 [running]> on host 2ac721f319c6
[2024-05-09T17:14:12.731+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T00:00:00+00:00'
[2024-05-09T17:14:12.733+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T17:14:12.792+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T17:14:12.793+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T17:14:12.803+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T00:00:00+00:00, execution_date=20240509T000000, start_date=20240509T171412, end_date=20240509T171412
[2024-05-09T17:14:12.828+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T17:14:12.845+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T17:14:12.848+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T18:32:07.970+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T18:32:08.115+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-09T18:32:08.142+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T00:00:00+00:00 [queued]>
[2024-05-09T18:32:08.143+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T18:32:08.199+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 00:00:00+00:00
[2024-05-09T18:32:08.206+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=412) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T18:32:08.208+0000] {standard_task_runner.py:63} INFO - Started process 428 to run task
[2024-05-09T18:32:08.208+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmp8wa8i9a2']
[2024-05-09T18:32:08.210+0000] {standard_task_runner.py:91} INFO - Job 54: Subtask except_friday_run_database_task
[2024-05-09T18:32:08.268+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T18:32:08.463+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T00:00:00+00:00 [running]> on host def55370f167
[2024-05-09T18:32:08.921+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T00:00:00+00:00'
[2024-05-09T18:32:08.926+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T18:32:09.038+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T18:32:09.040+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/single_dag.py", line 101, in insert_data_to_table
    cur.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.

[2024-05-09T18:32:09.102+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T00:00:00+00:00, execution_date=20240509T000000, start_date=20240509T183208, end_date=20240509T183209
[2024-05-09T18:32:09.151+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 54 for task except_friday_run_database_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.
; 428)
[2024-05-09T18:32:09.189+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T18:32:09.287+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T18:32:09.295+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
