[2024-05-09T10:00:02.655+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T10:00:02.680+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T08:00:00+00:00 [queued]>
[2024-05-09T10:00:02.687+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T08:00:00+00:00 [queued]>
[2024-05-09T10:00:02.688+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T10:00:02.698+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 08:00:00+00:00
[2024-05-09T10:00:02.702+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1678) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T10:00:02.703+0000] {standard_task_runner.py:63} INFO - Started process 1679 to run task
[2024-05-09T10:00:02.702+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T08:00:00+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmp5e1tnjtp']
[2024-05-09T10:00:02.704+0000] {standard_task_runner.py:91} INFO - Job 71: Subtask except_friday_run_database_task
[2024-05-09T10:00:02.717+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T10:00:02.748+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T08:00:00+00:00 [running]> on host 5d069ed3d57a
[2024-05-09T10:00:02.821+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T08:00:00+00:00'
[2024-05-09T10:00:02.822+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T10:00:02.849+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T10:00:02.850+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T10:00:02.859+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T08:00:00+00:00, execution_date=20240509T080000, start_date=20240509T100002, end_date=20240509T100002
[2024-05-09T10:00:02.876+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T10:00:02.890+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T10:00:02.892+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T17:14:12.376+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T17:14:12.415+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T08:00:00+00:00 [queued]>
[2024-05-09T17:14:12.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T08:00:00+00:00 [queued]>
[2024-05-09T17:14:12.424+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T17:14:12.439+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 08:00:00+00:00
[2024-05-09T17:14:12.448+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=273) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T17:14:12.450+0000] {standard_task_runner.py:63} INFO - Started process 278 to run task
[2024-05-09T17:14:12.451+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T08:00:00+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpqojqr2kk']
[2024-05-09T17:14:12.454+0000] {standard_task_runner.py:91} INFO - Job 197: Subtask except_friday_run_database_task
[2024-05-09T17:14:12.476+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T17:14:12.548+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T08:00:00+00:00 [running]> on host 2ac721f319c6
[2024-05-09T17:14:12.704+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T08:00:00+00:00'
[2024-05-09T17:14:12.706+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T17:14:12.756+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T17:14:12.759+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T17:14:12.775+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T08:00:00+00:00, execution_date=20240509T080000, start_date=20240509T171412, end_date=20240509T171412
[2024-05-09T17:14:12.831+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T17:14:12.848+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T17:14:12.851+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T18:32:07.994+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T18:32:08.115+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T08:00:00+00:00 [queued]>
[2024-05-09T18:32:08.132+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T08:00:00+00:00 [queued]>
[2024-05-09T18:32:08.133+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T18:32:08.177+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 08:00:00+00:00
[2024-05-09T18:32:08.186+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=414) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T18:32:08.186+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T08:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpn4rpmuh5']
[2024-05-09T18:32:08.188+0000] {standard_task_runner.py:63} INFO - Started process 427 to run task
[2024-05-09T18:32:08.189+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask except_friday_run_database_task
[2024-05-09T18:32:08.253+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T18:32:08.476+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T08:00:00+00:00 [running]> on host def55370f167
[2024-05-09T18:32:08.914+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T08:00:00+00:00'
[2024-05-09T18:32:08.915+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T18:32:09.040+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T18:32:09.041+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/single_dag.py", line 101, in insert_data_to_table
    cur.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.

[2024-05-09T18:32:09.115+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T08:00:00+00:00, execution_date=20240509T080000, start_date=20240509T183208, end_date=20240509T183209
[2024-05-09T18:32:09.150+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task except_friday_run_database_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.
; 427)
[2024-05-09T18:32:09.172+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T18:32:09.269+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T18:32:09.281+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
