[2024-05-09T09:13:43.044+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T09:13:43.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T06:00:00+00:00 [queued]>
[2024-05-09T09:13:43.083+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T06:00:00+00:00 [queued]>
[2024-05-09T09:13:43.084+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T09:13:43.095+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 06:00:00+00:00
[2024-05-09T09:13:43.100+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=298) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T09:13:43.101+0000] {standard_task_runner.py:63} INFO - Started process 303 to run task
[2024-05-09T09:13:43.100+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T06:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmp9z5a44lv']
[2024-05-09T09:13:43.102+0000] {standard_task_runner.py:91} INFO - Job 63: Subtask except_friday_run_database_task
[2024-05-09T09:13:43.115+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T09:13:43.150+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T06:00:00+00:00 [running]> on host 5d069ed3d57a
[2024-05-09T09:13:43.225+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T06:00:00+00:00'
[2024-05-09T09:13:43.226+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T09:13:43.253+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T09:13:43.254+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T09:13:43.263+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T06:00:00+00:00, execution_date=20240509T060000, start_date=20240509T091343, end_date=20240509T091343
[2024-05-09T09:13:43.274+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T09:13:43.290+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T09:13:43.292+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T17:14:12.382+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T17:14:12.424+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T06:00:00+00:00 [queued]>
[2024-05-09T17:14:12.437+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T06:00:00+00:00 [queued]>
[2024-05-09T17:14:12.438+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T17:14:12.456+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 06:00:00+00:00
[2024-05-09T17:14:12.463+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=272) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T17:14:12.465+0000] {standard_task_runner.py:63} INFO - Started process 282 to run task
[2024-05-09T17:14:12.465+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T06:00:00+00:00', '--job-id', '199', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpg8oheweu']
[2024-05-09T17:14:12.467+0000] {standard_task_runner.py:91} INFO - Job 199: Subtask except_friday_run_database_task
[2024-05-09T17:14:12.488+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T17:14:12.537+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T06:00:00+00:00 [running]> on host 2ac721f319c6
[2024-05-09T17:14:12.676+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T06:00:00+00:00'
[2024-05-09T17:14:12.679+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T17:14:12.721+0000] {logging_mixin.py:188} INFO - Successfully created table 'incidence_table'
[2024-05-09T17:14:12.728+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-09T17:14:12.730+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T17:14:12.749+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T06:00:00+00:00, execution_date=20240509T060000, start_date=20240509T171412, end_date=20240509T171412
[2024-05-09T17:14:12.769+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-09T17:14:12.797+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T17:14:12.799+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-09T18:32:07.984+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-09T18:32:08.119+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T06:00:00+00:00 [queued]>
[2024-05-09T18:32:08.133+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T06:00:00+00:00 [queued]>
[2024-05-09T18:32:08.133+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-09T18:32:08.167+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): except_friday_run_database_task> on 2024-05-09 06:00:00+00:00
[2024-05-09T18:32:08.174+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=413) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-09T18:32:08.174+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'days_except_friday_dag', 'except_friday_run_database_task', 'scheduled__2024-05-09T06:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/single_dag.py', '--cfg-path', '/tmp/tmpn5fb2stu']
[2024-05-09T18:32:08.176+0000] {standard_task_runner.py:63} INFO - Started process 425 to run task
[2024-05-09T18:32:08.177+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask except_friday_run_database_task
[2024-05-09T18:32:08.241+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-05-09T18:32:08.455+0000] {task_command.py:426} INFO - Running <TaskInstance: days_except_friday_dag.except_friday_run_database_task scheduled__2024-05-09T06:00:00+00:00 [running]> on host def55370f167
[2024-05-09T18:32:08.853+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='days_except_friday_dag' AIRFLOW_CTX_TASK_ID='except_friday_run_database_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-09T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-09T06:00:00+00:00'
[2024-05-09T18:32:08.858+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-09T18:32:09.038+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-09T18:32:09.040+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/single_dag.py", line 101, in insert_data_to_table
    cur.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.

[2024-05-09T18:32:09.108+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=days_except_friday_dag, task_id=except_friday_run_database_task, run_id=scheduled__2024-05-09T06:00:00+00:00, execution_date=20240509T060000, start_date=20240509T183208, end_date=20240509T183209
[2024-05-09T18:32:09.147+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task except_friday_run_database_task (duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(incidence_table_id_seq, 2200) already exists.
; 425)
[2024-05-09T18:32:09.201+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-09T18:32:09.289+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-09T18:32:09.299+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
